services:
    dv.oauth:
        class: Druidvav\SimpleOauthBundle\Service\OAuthService
        calls:
            - [ setContainer, [ "@service_container" ] ]
    dv.oauth.http_client:
        class: Buzz\Client\Curl
        calls:
            - [ setVerifyPeer, [ false ] ]
            - [ setTimeout, [ 5 ] ]
            - [ setMaxRedirects, [ 1 ] ]
            - [ setIgnoreErrors, [ false ] ]
    dv.oauth.storage.session:
        class: Druidvav\SimpleOauthBundle\OAuth\RequestDataStorage\SessionStorage
        arguments: [ "@session" ]
