services:
    dv.oauth:
        class: Druidvav\SimpleOauthBundle\Service\OAuthService
        calls:
            - [ setContainer, [ "@service_container" ] ]
    dv.oauth.http_client:
        class: Buzz\Client\Curl
        arguments:
            max_redirects: 1
            timeout: 5
            verify: false
    dv.oauth.storage.session:
        class: Druidvav\SimpleOauthBundle\OAuth\RequestDataStorage\SessionStorage
        arguments: [ "@session" ]
