services:
    dv.oauth:
        class: Druidvav\SimpleOauthBundle\Service\OAuthService
        calls:
            - [ setContainer, [ "@service_container" ] ]
    dv.oauth.http_client:
        class: Http\Client\Common\HttpMethodsClient
        arguments: [ "@dv.oauth.http.client" , "@dv.oauth.http.message_factory" ]
    dv.oauth.storage.session:
        class: Druidvav\SimpleOauthBundle\OAuth\RequestDataStorage\SessionStorage
        arguments: [ "@session" ]
