services:
    dv.oauth:
        class: Druidvav\SimpleOauthBundle\Service\OAuthService
        calls:
            - [ setContainer, [ "@service_container" ] ]
    dv.oauth.http_client:
        class: Http\Client\Common\HttpMethodsClient
        arguments: [ "hwi_oauth.http.client" , "hwi_oauth.http.message_factory" ]


        <service id="hwi_oauth.http_client" class="" public="true">
            <argument type="service" id="hwi_oauth.http.client"/>
            <argument type="service" id="hwi_oauth.http.message_factory"/>
        </service>
    dv.oauth.storage.session:
        class: Druidvav\SimpleOauthBundle\OAuth\RequestDataStorage\SessionStorage
        arguments: [ "@session" ]
